hmcts/snl-events

docker-compose.yml, infrastructure/main.tf, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/controllers/SessionController.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/converters/DurationConverter.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/mappers/DurationToSecondsSerializer.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/mappers/SessionMapper.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/messages/FactMessage.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/model/Problem.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/model/Session.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/repository/ProblemRepository.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/repository/SessionRepository.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/FactMessageService.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/RulesService.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/SessionService.java, src/main/resources/application.yaml, src/main/resources/db/db-changelog.yaml, src/main/resources/db/schema/SL-892-problem.yaml
https://tools.hmcts.net/jira/browse/SL-892
=> SL-892 implemented call to rules engine and persisting probllems to db

src/main/java/uk/gov/hmcts/reform/sandl.snlevents/controllers/SessionController.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/model/response/ProblemResponse.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/ProblemService.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/SessionService.java
=> return session on creation and add message

src/main/java/uk/gov/hmcts/reform/sandl.snlevents/controllers/HearingPartController.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/model/db/UserTransactionData.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/model/request/HearingPartSessionRelationship.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/model/usertransaction/UserTransactionStatus.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/repository/db/UserTransactionDataRepository.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/HearingPartService.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/RevertChangesManager.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/UserTransactionService.java
=> Feature/sl 964/pessimistic locking

src/main/resources/db/db-changelog.yaml, src/main/resources/db/fixtures/SL-964-set-started-transactions-to-comitted.yaml, src/main/resources/db/schema/SL-964-set-all-transactions-to-comitted.yaml
=> Add migration to change STARTED transactions to COMITTED

src/main/java/uk/gov/hmcts/reform/sandl.snlevents/controllers/SessionController.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/controllers/UserTransactionController.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/mappers/FactsMapper.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/model/request/UpsertSession.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/HearingPartService.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/RevertChangesManager.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/SessionService.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/UserTransactionService.java
=> Feature/sl 954/drag and drop

src/main/java/uk/gov/hmcts/reform/sandl.snlevents/service/HearingPartService.java
=> set transaction id when assigning hearing part

src/main/java/uk/gov/hmcts/reform/sandl.snlevents/controllers/ReportController.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/model/report/ListedHearingRequestReportResult.java, src/main/java/uk/gov/hmcts/reform/sandl.snlevents/repository/db/HearingPartRepository.java
=> Fix checkstyle

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/Availability.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/HearingPart.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/Session.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/UserTransaction.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/response/SessionInfo.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/rules/FactAvailability.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/rules/FactHearingPart.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/rules/FactSession.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/FactMessageService.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/RevertChangesManager.java
=> SL-995 changes related to SonarQube code smells list, mostly squid:S3437

src/test/java/uk/gov/hmcts/reform/sandl/snlevents/services/UserTransactionServiceTests.java
Added unit tests for UserTransactionService
=> UserTransactionService - Unit tests

docker/snl-db/Dockerfile
=> SL-1098 changed to postgres 10

src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/BaseIntegrationTest.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/TestConfiguration.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/fakerules/BaseIntegrationTestWithFakeRules.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/fakerules/repository/SessionRepositoryTest.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/fakerules/service/HearingPartServiceTest.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/fakerules/service/SessionServiceTest.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/testdata/builders/HearingPartBuilder.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/testdata/builders/SessionBuilder.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/testdata/builders/UpsertSessionBuilder.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/testdata/helpers/OffsetDateTimeHelper.java, src/test/resources/config/application.yaml
=> Feature/sl 1056/integration tests

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/HearingPartController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/HearingPart.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/request/CreateHearingPart.java, src/main/resources/db/db-changelog.yaml, src/main/resources/db/schema/SL-1108-add-columns-to-hearing-part-table.yaml, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/HearingPartControllerTest.java, tools/hooks/prepare-commit-msg
Added 2 body params to create hearing model, extended hearing-part table, updated unit test
Added missing hook script
=> SL-1108 add additional attributes to hearing part + Hooks

tools/reference-data-parser/.gitignore, tools/reference-data-parser/generate-sql.js, tools/reference-data-parser/package-lock.json, tools/reference-data-parser/package.json
Simple Node script that parses ReferenceData excel file and generates SQL statements
For internal (devs) use only
=> SL-1348 & SL-1349 Reference data parser

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/HearingPartController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/HearingPart.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/HearingPartService.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/RulesService.java, src/main/resources/db/db-changelog.yaml, src/main/resources/db/schema/SL-1111-add-is-deleted-column-to-hearing-part-table.yaml, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/common/EventsMockMvc.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/HearingPartControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/HearingPartServiceTest.java
https://tools.hmcts.net/jira/browse/SL-1111
added delete hearing part endpoint to events
```
[ ] Yes
[x] No
```
=> SL-1111 delete hearing part endpoint

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/actions/listingrequest/DeleteListingRequestAction.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/HearingPartController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/request/DeleteListingRequest.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/HearingPartService.java, src/main/resources/application.yaml, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/fakerules/service/HearingPartServiceTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/actions/DeleteListingRequestActionTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/common/EventsMockMvc.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/HearingPartControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/SessionControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/HearingPartServiceTest.java
=> Feature/sl 1111/delete transactional

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/SessionController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/response/SessionInfo.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/repository/queries/SessionQueries.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/SessionService.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/SessionControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/SessionServiceTest.java
=> [PREVIEW] Feature/sl 1595/sessiontype list hearings

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/request/UpsertSession.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/SessionService.java
=> SL-1483 Capture an individual session - compatibility fix

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/PostDbDataController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/mappers/FactsMapper.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/Session.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/request/UpsertSession.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/response/SessionInfo.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/rules/FactCaseType.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/rules/FactHearingPart.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/rules/FactHearingType.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/rules/FactSession.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/rules/FactSessionType.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/RulesService.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/SessionService.java, src/main/resources/application.yaml, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/testdata/builders/UpsertSessionBuilder.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/mappers/FactsMapperTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/SessionServiceTest.java
=> [PREVIEW] Feature/sl 1351 refdata rules

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/mappers/FactsMapper.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/mappers/FactsMapperTest.java
=> fix sessiontypecode

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/CaseType.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/HearingType.java
=> SL-1524: Fix infinite loop with casetypes and sessiontypes

run.sh, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/config/JacksonConfig.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/Problem.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/request/CreateProblem.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/response/ProblemResponse.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/FactMessageService.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/ProblemService.java, src/main/resources/db/db-changelog.yaml, src/main/resources/db/schema/SL-1516-add-createdAt-to-problem-table.yaml, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/FactMessageServiceTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/ProblemServiceTest.java
Added new column to Problem table (createdAt)
set date time format for object mapper (the same as rules produce)
=> [PREVIEW] SL-1516 add additional detail to display on problems page

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/RoomController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/response/RoomResponse.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/RoomService.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/RoomControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/RoomServiceTest.java
=> SL-1489: Set roomtypecode on rooms

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/db/Session.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/repository/queries/SessionQueries.java, src/main/resources/db/db-changelog.yaml, src/main/resources/db/schema/SL-1608-remove-casetype.yaml, src/main/resources/db/testdata/insert-testdata.sql, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/fakerules/repository/SessionRepositoryTest.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/fakerules/service/HearingPartServiceTest.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/testdata/builders/SessionBuilder.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/SessionControllerTest.java
=> [PREVIEW] SL-1608: remove case type

infrastructure/main.tf, src/main/resources/application.yaml
=> [PREVIEW] - extend timeout

infrastructure/main.tf, infrastructure/outputs.tf, infrastructure/variables.tf, src/main/resources/application.yaml
=> [PREVIEW] SL-1722 added reading jwt form shared vault

infrastructure/main.tf
=> Sl-1722 not needed secret removed

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/repository/db/ProblemRepository.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/ProblemService.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/repositories/ProblemRepositoryTests.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/ProblemServiceTest.java
=> [PREVIEW] SL-1564 Sort problems by descending date of creation within severity

src/main/resources/db/testdata/insert-testdata.sql
https://tools.hmcts.net/jira/browse/SL-1698
```
[ ] Yes
[x] No
```
=> [PREVIEW] SL-1698: fix test data

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
=> [PREVIEW] SL-1872 added shared infra

build.gradle
=> [PREVIEW] fix coverage

build.gradle, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/actions/listingrequest/DeleteListingRequestAction.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/actions/session/AmendSessionAction.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/repository/db/ProblemRepository.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/repository/queries/ProblemQueries.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/HearingPartService.java, src/test/integration/uk/gov/hmcts/reform/sandl/snlevents/repositories/ProblemRepositoryTests.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/HearingPartServiceTest.java
=> [PREVIEW] SL-1876 removed gradle exclusions for tests

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/repository/queries/HearingQueries.java
added join in query so the date is taken from session not from hearing_part
=> [PREVIEW] SL-1551 fix column to be session start rather than hearingpart

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/actions/hearingpart/AssignHearingPartToSessionAction.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/actions/hearingpart/AssignHearingPartToSessionActionTest.java
added setStart() and updated tests
```
[ ] Yes
[X] No
```
=> [PREVIEW] Feature/sl 1787/listing to session start 2

infrastructure/main.tf
=> [PREVIEW] SL-2107: set the capacity and size - workaround for RDO-2917

build.gradle, dependency-check-suppressions.xml, infrastructure/main.tf
upgrade libs and correct cuppressions
=> [PREVIEW] SL-997-: Update dependency-check-suppressions.xml

gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/scheduledtasks/RulesScheduledTasks.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/scheduledtasks/RulesScheduledTasksTest.java
just shows nice message in intellij rather than a big stack trace, (which is still available in debug if needed)
=> more friendly error handling for scheduled tasks

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/repository/queries/HearingQueries.java
Amended the subquery to join persons table to hearing table
```
[ ] Yes
[X ] No
```
=> [PREVIEW] bugfix/sl 2104/judge name search listings

Jenkinsfile_CNP, Jenkinsfile_parameterized, src/kubernetes/config.aat.yaml, src/kubernetes/config.saat.yaml, src/kubernetes/deployment.template.yaml
=> [AKS] SL-1919: enabling AKS for sandbox

src/main/java/uk/gov/hmcts/reform/sandl/snlevents/actions/session/DragAndDropSessionAction.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/HearingPartController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/SessionController.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/request/DeleteListingRequest.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/model/request/DragAndDropSessionRequest.java, src/main/java/uk/gov/hmcts/reform/sandl/snlevents/service/SessionService.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/actions/session/AmendSessionActionTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/actions/session/DragAndDropSessionActionTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/HearingPartControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/controllers/SessionControllerTest.java, src/test/java/uk/gov/hmcts/reform/sandl/snlevents/service/SessionServiceTest.java
Added DragAndDropSession Action + unit test
=> [AKS] SL-1794 Additional action when changing joh for a session with multi part hearing via planner
